### ISSUE TITLE
Weird underline with vim syntax enhancers

### ISSUE THREAD

**Issue by joniva** [Dru89/vim-adventurous#1]
When I use external syntax highlighters for vim I get weird underlines on some parts of the code, would it be possible to remove it?

![image](https://user-images.githubusercontent.com/49179489/83593939-c87f4600-a512-11ea-9019-3c044ee90544.png)

This issue is present with two completely different syntax highlighters (c++ and lua)
For reference: 
https://github.com/octol/vim-cpp-enhanced-highlight  
https://github.com/tbastos/vim-lua
System: Windows 10

**Comment by joniva** [comment]
Nevermind, I fixed this by removing all instances of underline in the vim file. Cool colorscheme thanks.

**Comment by dru89** [comment]
I'm glad you like it! I … actually never got around to finishing this. But if you want to support underline maybe I can pick this back up at some point (or I'd take contributions, too). 😄

**Comment by dru89** [comment]
There also appears to be https://github.com/kitten/vim-adventurous! TIL
